# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule: [{cron: "0 0 1 * *"}]
  workflow_dispatch:
  push: 
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: activity
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: activity.svg
          token: ${{ secrets.TOKEN }}
          # Options
          base: activity
          base_indepth: yes
          config_timezone: Asia/Dubai
          plugin_lines: yes
          plugin_lines_history_limit: 2
          plugin_lines_repositories_limit: 10
          plugin_lines_sections: base
          
      - name: grid
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: grid.svg
          token: ${{ secrets.TOKEN }}
          # Options
          base: ""
          base_indepth: yes
          config_display: large
          config_timezone: Asia/Dubai
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      - name: languages
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.TOKEN }}
          # Options
          base: ""
          base_indepth: yes
          config_timezone: Asia/Dubai
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 10
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: c++,java
          plugin_languages_limit: 15
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
